version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Port tempat aplikasi Koa.js berjalan
    depends_on:
      - mysql
      - couchdb
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${MYSQL_PORT}/${MYSQL_DATABASE}
      - COUCHDB_URL=http://${COUCHDB_USER}:${COUCHDB_PASS}@couchdb:5984
      - COUCHDB_NAME=shortlink
    env_file:
      - .env

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306" # Port MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984" # Port CouchDB
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASS}
